trigger: none
pr:
  branches:
    include:
      - main

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - stage: InitStage
        displayName: Initialize
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: InitJob
            displayName: Initialize
            steps:
              - pwsh: |
                  Write-Host "Setting RunCore to true"
                  Write-Host "##vso[task.setvariable variable=RunCore;isOutput=true]true"
                  Write-Host "Setting RunCSharp to true"
                  Write-Host "##vso[task.setvariable variable=RunCSharp;isOutput=true]true"
                  Write-Host "Setting RunPython to true"
                  Write-Host "##vso[task.setvariable variable=RunPython;isOutput=true]true"
                name: InitStep
                displayName: Initialize

      # Run csharp stages if RunCSharp == true
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCSharp'])

      # Run core stages if RunCore == true
      - stage: Build_Core
        displayName: Build Core
        dependsOn: InitStage
        condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore'])
        variables:
          - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self
        jobs:
          - job: windows
            displayName: Windows

            variables:
              TYPESPEC_VS_CI_BUILD: true # Enable official Visual Studio extension build
              TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

            strategy:
              matrix:
                "Node 18.x":
                  nodeVersion: 18.x

                "Node 20.x":
                  nodeVersion: 20.x

            pool:
              name: $(WINDOWSPOOL)
              image: $(WINDOWSVMIMAGE)
              os: windows

            steps:
              - template: /eng/tsp-core/pipelines/jobs/build-and-test.yml
                parameters:
                  nodeVersion: $(nodeVersion)
                  os: linux

          - job: linux
            displayName: Linux

            variables:
              TYPESPEC_VS_CI_BUILD: true # Enable official Visual Studio extension build
              TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

            strategy:
              matrix:
                "Node 18.x":
                  nodeVersion: 18.x

                "Node 20.x":
                  nodeVersion: 20.x

            pool:
              name: $(LINUXPOOL)
              image: $(LINUXVMIMAGE)
              os: linux

            steps:
              - template: /eng/tsp-core/pipelines/jobs/build-and-test.yml
                parameters:
                  nodeVersion: $(nodeVersion)
                  os: linux

          - template: /eng/tsp-core/pipelines/jobs/publish-artifacts.yml
          - template: /eng/tsp-core/pipelines/jobs/e2e.yml

          - job: docker_build
            pool:
              name: $(LINUXPOOL)
              image: $(LINUXVMIMAGE)
              os: linux
            steps:
              - script: docker build -f ./docker/Dockerfile .
                displayName: Docker build
