trigger: none
pr:
  branches:
    include:
      - main

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - stage: InitStage
        displayName: Initialize
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: InitJob
            displayName: Initialize
            steps:
              - pwsh: |
                  # set RunCore to true if changes were made outside of /packages/http-client-csharp
                  if (git diff --name-only HEAD^ HEAD | Select-String -Pattern "^(?!packages/http-client-csharp)" -Quiet) {
                    Write-Host "Changes were made outside of /packages/http-client-csharp"
                    Write-Host "Setting RunCore to true"
                    Write-Host "##vso[task.setvariable variable=RunCore;isOutput=true]true"
                  }
                  # set RunCSharp to true if changes were made inside of /packages/http-client-csharp
                  if (git diff --name-only HEAD^ HEAD | Select-String -Pattern "^packages/http-client-csharp" -Quiet) {
                    Write-Host "Changes were made inside of /packages/http-client-csharp"
                    Write-Host "Setting RunCSharp to true"
                    Write-Host "##vso[task.setvariable variable=RunCSharp;isOutput=true]true"
                  }
                name: InitStep
                displayName: Initialize

      # Run csharp stages if RunCSharp == true
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCSharp'])

      # Run core stages if RunCore == true
      - template: /eng/tsp-core/pipelines/stages/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore'])
