stages:
  - stage: InitStage
    displayName: Initialize
    jobs:
      - job: InitJob
        displayName: Initialize
        steps:
          - pwsh: |
              # emit a pipeline output variable called RunCSharp
              Write-Host "Setting RunCSharp to true"
              Write-Host "##vso[task.setvariable variable=RunCSharp;isOutput=true]true"
              Write-Host "Setting RunPython to true"
              Write-Host "##vso[task.setvariable variable=RunPython;isOutput=true]true"
            name: InitStep
            displayName: Initialize

  - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
    parameters:
      DependsOn: InitStage
      Condition: $[stageDependencies.InitStage.InitJob.outputs['InitStep.RunCSharp'] == 'true']
