trigger: none

pr: none

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
