trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - packages/http-client-csharp/
      - eng/emitters/
      - eng/common/

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - template: /packages/http-client-csharp/eng/pipeline/templates\ci-stages.yml
